version: '3.7'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  prices_app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: prices_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python3 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8080

  worker:
    build:
      dockerfile: Dockerfile
      context: .
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - prices_app
      - redis

  dashboard:
    build:
      dockerfile: Dockerfile
      context: .
    command: celery -A worker.celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - prices_app
      - redis
      - worker

volumes:
  redis_data: